name: Get Metadata
description: "Gets build metadata."
runs:
  using: "composite"
  steps:
    - name: Get Metadata
      id: metadata
      shell: bash
      run: |
        datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
        echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
        echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
        echo "terraform_version=$(cat .terraform-version | cut -f2 -d' ')" >> $GITHUB_OUTPUT
        echo "terragrunt_version=$(cat .terragrunt-version | cut -f2 -d' ')" >> $GITHUB_OUTPUT