# {% raw %}
name: Check Terraform Format
description: Check Terraform Format
runs:
  using: "composite"
  steps:
    - name: Grant execute permissions to the script
      shell: bash
      run: chmod +x ./.github/scripts/githooks/check-terraform-format.sh

    - name: Check Terraform Format
      shell: bash
      run: |
        export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
        ./.github/scripts/githooks/check-terraform-format.sh
# {% endraw %}